loc add item to cart by name: id=add-to-cart-${dash separated itemname}
loc sorting dropdown: data-test=product-sort-container
loc sorting option value:
  price asc: lohi
  price desc: hilo
  A to Z: az
  Z to A: za
loc item name label: css=div.inventory_item_name
loc item price label: css=div.inventory_item_price